services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE budgetweb;" -U postgres
  - psql -c "CREATE DATABASE travis;" -U postgres
  - psql -c "CREATE USER budgetweb WITH PASSWORD 'budgetweb';" -U postgres
  - psql -c "ALTER USER budgetweb CREATEUSER CREATEDB;"

variables:
  POSTGRES_DB: budgetweb
  POSTGRES_USER: budgetweb
  POSTGRES_PASSWORD: budgetweb

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install tox
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
